
services:
  app:
    build: .
    container_name: project-x
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - project-x-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - project-x-network

networks:
  project-x-network:
    driver: bridge
